/**
 * Text labels used by the product workspace.
 */
export type ProductWorkspaceLabels = {
  readonly addCombination: string
  readonly addCombinationMaterial: string
  readonly addMaterial: string
  readonly addPiece: string
  readonly cancel: string
  readonly canvasEmptyDescription: string
  readonly canvasEmptyTitle: string
  readonly canvasEfficiency: string
  readonly canvasFallbackError: string
  readonly canvasLabel: string
  readonly canvasLoadingPiece: string
  readonly canvasUnplaced: string
  readonly canvasUsed: string
  readonly canvasWaste: string
  readonly closeDialog: string
  readonly combinationColorLabel: string
  readonly combinationCreateTitle: string
  readonly combinationDeleteDescription: string
  readonly combinationDeleteTitle: string
  readonly combinationEmptyDescription: string
  readonly combinationEmptyTitle: string
  readonly combinationLabel: string
  readonly combinationMaterialAssignmentsLabel: string
  readonly combinationMaterialEmptyDescription: string
  readonly combinationMaterialMaterialLabel: string
  readonly combinationMaterialRoleLabel: string
  readonly combinationMaterialToggleLabel: string
  readonly combinationNameLabel: string
  readonly combinationNamePlaceholder: string
  readonly combinationRemovedToast: string
  readonly combinationSavedToast: string
  readonly combinations: string
  readonly combinationsPanelDescription: string
  readonly consumption: string
  readonly consumptionDecreaseUnits: string
  readonly consumptionEfficiency: string
  readonly consumptionEmptyDescription: string
  readonly consumptionLength: string
  readonly consumptionMeters: string
  readonly consumptionPanelDescription: string
  readonly consumptionSheets: string
  readonly consumptionUnitsLabel: string
  readonly consumptionIncreaseUnits: string
  readonly consumptionUsed: string
  readonly consumptionWaste: string
  readonly createCatalogMaterial: string
  readonly createCombination: string
  readonly createPiece: string
  readonly deleteCombination: string
  readonly deleteMaterial: string
  readonly deletePiece: string
  readonly deleting: string
  readonly despieceView: string
  readonly downloadDialogDescription: string
  readonly downloadDialogTitle: string
  readonly downloadFormatDxf: string
  readonly downloadFormatLabel: string
  readonly downloadFormatPdf: string
  readonly downloadScopeCombined: string
  readonly downloadScopeLabel: string
  readonly downloadScopePerMaterial: string
  readonly downloadScopePerPliego: string
  readonly downloadScopePerSheet: string
  readonly downloading: string
  readonly editCombination: string
  readonly editPiece: string
  readonly export: string
  readonly formErrorToast: string
  readonly home: string
  readonly materialCatalogEmptyDescription: string
  readonly materialCatalogSearchLabel: string
  readonly materialCatalogSearchPlaceholder: string
  readonly materialColorLabel: string
  readonly materialDeleteDescription: string
  readonly materialDeleteTitle: string
  readonly materialEmptyDescription: string
  readonly materialEmptyTitle: string
  readonly materialIconLabel: string
  readonly materialIconSearchLabel: string
  readonly materialIconSearchPlaceholder: string
  readonly materialNameLabel: string
  readonly materialNamePlaceholder: string
  readonly materialRemovedToast: string
  readonly materialSavedToast: string
  readonly materialSelectLabel: string
  readonly materialWidthLabel: string
  readonly materialWidthPlaceholder: string
  readonly materials: string
  readonly materialsPanelDescription: string
  readonly newCatalogMaterial: string
  readonly noCombination: string
  readonly nextSheet: string
  readonly pieceAddMaterialRequirement: string
  readonly pieceCombinationScopeEmptyDescription: string
  readonly pieceDeleteDescription: string
  readonly pieceDeleteTitle: string
  readonly pieceDxfChooseAction: string
  readonly pieceDxfCurrentLabel: string
  readonly pieceDxfDropHint: string
  readonly pieceDxfInvalidFile: string
  readonly pieceDxfLabel: string
  readonly pieceDxfPreviewLabel: string
  readonly pieceDxfSelectedLabel: string
  readonly pieceEmptyDescription: string
  readonly pieceEmptyTitle: string
  readonly pieceGlobalScopeEmptyDescription: string
  readonly pieceGlobalScopeLabel: string
  readonly pieceHeightLabel: string
  readonly pieceMaterialsLabel: string
  readonly pieceNameLabel: string
  readonly pieceNamePlaceholder: string
  readonly pieceNumberLabel: string
  readonly pieceQuantityLabel: string
  readonly pieceRemovedToast: string
  readonly pieceRemoveMaterialRequirement: string
  readonly pieceReplaceDxfLabel: string
  readonly pieceSave: string
  readonly pieceSavedToast: string
  readonly pieceScopeAllLabel: string
  readonly pieceWidthLabel: string
  readonly pieces: string
  readonly piecesPanelDescription: string
  readonly previousSheet: string
  readonly product: string
  readonly productPanelDescription: string
  readonly productionCutView: string
  readonly productionMaterialLabel: string
  readonly productionNoMaterialDescription: string
  readonly productionSheetLabel: string
  readonly removeCombinationMaterial: string
  readonly saveCombination: string
  readonly saveMaterial: string
  readonly saving: string
  readonly selectExistingMaterial: string
  readonly sidebarTitle: string
  readonly stickers: string
  readonly stickersPanelDescription: string
  readonly updated: string
  readonly uploads: string
  readonly uploadsPanelDescription: string
  readonly viewLabel: string
  readonly workspace: string
  readonly zoomCenter: string
  readonly zoomIn: string
  readonly zoomOut: string
  readonly zoomReset: string
}
