import type { getTranslations } from 'next-intl/server'

import type { ProductWorkspaceLabels } from './product-workspace.types'

/**
 * Builds translated workspace labels.
 *
 * @param t - Product workspace translation helper.
 * @returns Workspace labels.
 */
export function getWorkspaceLabels(
  t: Awaited<ReturnType<typeof getTranslations>>
): ProductWorkspaceLabels {
  return {
    addCombination: t('addCombination'),
    addCombinationMaterial: t('addCombinationMaterial'),
    addMaterial: t('addMaterial'),
    addPiece: t('addPiece'),
    cancel: t('cancel'),
    canvasEmptyDescription: t('canvasEmptyDescription'),
    canvasEmptyTitle: t('canvasEmptyTitle'),
    canvasEfficiency: t('canvasEfficiency'),
    canvasFallbackError: t('canvasFallbackError'),
    canvasLabel: t('canvasLabel'),
    canvasLoadingPiece: t('canvasLoadingPiece'),
    canvasUnplaced: t('canvasUnplaced'),
    canvasUsed: t('canvasUsed'),
    canvasWaste: t('canvasWaste'),
    closeDialog: t('closeDialog'),
    combinationColorLabel: t('combinationColorLabel'),
    combinationCreateTitle: t('combinationCreateTitle'),
    combinationDeleteDescription: t('combinationDeleteDescription'),
    combinationDeleteTitle: t('combinationDeleteTitle'),
    combinationEmptyDescription: t('combinationEmptyDescription'),
    combinationEmptyTitle: t('combinationEmptyTitle'),
    combinationLabel: t('combinationLabel'),
    combinationMaterialAssignmentsLabel: t('combinationMaterialAssignmentsLabel'),
    combinationMaterialEmptyDescription: t('combinationMaterialEmptyDescription'),
    combinationMaterialMaterialLabel: t('combinationMaterialMaterialLabel'),
    combinationMaterialRoleLabel: t('combinationMaterialRoleLabel'),
    combinationMaterialToggleLabel: t('combinationMaterialToggleLabel'),
    combinationNameLabel: t('combinationNameLabel'),
    combinationNamePlaceholder: t('combinationNamePlaceholder'),
    combinations: t('combinations'),
    combinationsPanelDescription: t('combinationsPanelDescription'),
    createCatalogMaterial: t('createCatalogMaterial'),
    createCombination: t('createCombination'),
    createPiece: t('createPiece'),
    deleteCombination: t('deleteCombination'),
    deleteMaterial: t('deleteMaterial'),
    deletePiece: t('deletePiece'),
    deleting: t('deleting'),
    despieceView: t('despieceView'),
    editCombination: t('editCombination'),
    editPiece: t('editPiece'),
    export: t('export'),
    home: t('home'),
    materialCatalogEmptyDescription: t('materialCatalogEmptyDescription'),
    materialCatalogSearchLabel: t('materialCatalogSearchLabel'),
    materialCatalogSearchPlaceholder: t('materialCatalogSearchPlaceholder'),
    materialColorLabel: t('materialColorLabel'),
    materialDeleteDescription: t('materialDeleteDescription'),
    materialDeleteTitle: t('materialDeleteTitle'),
    materialEmptyDescription: t('materialEmptyDescription'),
    materialEmptyTitle: t('materialEmptyTitle'),
    materialIconLabel: t('materialIconLabel'),
    materialIconSearchLabel: t('materialIconSearchLabel'),
    materialIconSearchPlaceholder: t('materialIconSearchPlaceholder'),
    materialNameLabel: t('materialNameLabel'),
    materialNamePlaceholder: t('materialNamePlaceholder'),
    materialSelectLabel: t('materialSelectLabel'),
    materialWidthLabel: t('materialWidthLabel'),
    materialWidthPlaceholder: t('materialWidthPlaceholder'),
    materials: t('materials'),
    materialsPanelDescription: t('materialsPanelDescription'),
    newCatalogMaterial: t('newCatalogMaterial'),
    noCombination: t('noCombination'),
    pieceAddMaterialRequirement: t('pieceAddMaterialRequirement'),
    pieceCombinationScopeEmptyDescription: t('pieceCombinationScopeEmptyDescription'),
    pieceDeleteDescription: t('pieceDeleteDescription'),
    pieceDeleteTitle: t('pieceDeleteTitle'),
    pieceDxfChooseAction: t('pieceDxfChooseAction'),
    pieceDxfCurrentLabel: t('pieceDxfCurrentLabel'),
    pieceDxfDropHint: t('pieceDxfDropHint'),
    pieceDxfInvalidFile: t('pieceDxfInvalidFile'),
    pieceDxfLabel: t('pieceDxfLabel'),
    pieceDxfPreviewLabel: t('pieceDxfPreviewLabel'),
    pieceDxfSelectedLabel: t('pieceDxfSelectedLabel'),
    pieceEmptyDescription: t('pieceEmptyDescription'),
    pieceEmptyTitle: t('pieceEmptyTitle'),
    pieceGlobalScopeEmptyDescription: t('pieceGlobalScopeEmptyDescription'),
    pieceGlobalScopeLabel: t('pieceGlobalScopeLabel'),
    pieceHeightLabel: t('pieceHeightLabel'),
    pieceMaterialsLabel: t('pieceMaterialsLabel'),
    pieceNameLabel: t('pieceNameLabel'),
    pieceNamePlaceholder: t('pieceNamePlaceholder'),
    pieceNumberLabel: t('pieceNumberLabel'),
    pieceQuantityLabel: t('pieceQuantityLabel'),
    pieceRemoveMaterialRequirement: t('pieceRemoveMaterialRequirement'),
    pieceReplaceDxfLabel: t('pieceReplaceDxfLabel'),
    pieceSave: t('pieceSave'),
    pieceScopeAllLabel: t('pieceScopeAllLabel'),
    pieceWidthLabel: t('pieceWidthLabel'),
    pieces: t('pieces'),
    piecesPanelDescription: t('piecesPanelDescription'),
    product: t('product'),
    productPanelDescription: t('productPanelDescription'),
    removeCombinationMaterial: t('removeCombinationMaterial'),
    saveCombination: t('saveCombination'),
    saveMaterial: t('saveMaterial'),
    saving: t('saving'),
    selectExistingMaterial: t('selectExistingMaterial'),
    sidebarTitle: t('sidebarTitle'),
    stickers: t('stickers'),
    stickersPanelDescription: t('stickersPanelDescription'),
    updated: t('updated'),
    uploads: t('uploads'),
    uploadsPanelDescription: t('uploadsPanelDescription'),
    viewLabel: t('viewLabel'),
    workspace: t('workspace'),
    zoomIn: t('zoomIn'),
    zoomOut: t('zoomOut'),
    zoomReset: t('zoomReset')
  }
}
